### PR TITLE
Change default RDS instance type to db.t3.small

### LINKED ISSUE #68: RDS database T2 instance is being retired
[Just a service message]

The current default RDS instance for the metadata service is:
https://github.com/outerbounds/terraform-aws-metaflow/blob/fd5b56e1a6644e573385324ad0110f5e1441fbc6/modules/datastore/variables.tf#L4

However, this instance will soon not be available.

AWS wrote this to me (shortened):

_You are receiving this notification because you have one or more Amazon RDS for PostgreSQL database instances running on db.m4, db.r4, or db.t2 instance types. We plan to retire all M4, R4, and T2 instances by April 2024. [...] **Reserved instances for db.m4, db.r4, and db.t2 will no longer be available for purchase beginning on June 30, 2023.**_

_**Depending on the instance type you choose to upgrade to, you may also need to upgrade your PostgreSQL database version. We recommend that you upgrade your database engine to PostgreSQL 13.4 or higher.** For more details on supported RDS DB instance classes for each engine version please refer to the Amazon RDS user guide._

### PR DESCRIPTION
**Pull request by ryewilson**
Closes #68 

The current default instance type is `db.t2.small`, but this is currently deprecated. This change makes it so that `db.t3.small` is used instead.

The deprecated status is shown at the bottom of the first table on [this page](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html)

image

### CODE REVIEW

**Comment by casperbiering** [comment]
@oavdeev Do you have time to take a look at this please?

**Comment by acsbendi** [comment]
@ryewilson Don't you think that actually a `db.t3.micro` would be enough?

**Comment by ryewilson** [comment]
> @ryewilson Don't you think that actually a `db.t3.micro` would be enough?

I changed it to `db.t3.small` because it was previously `db.t2.small`, and t3.small is the most similar replacement. I assume there was a reason that `db.t2.small` was used instead of `db.t2.micro`.

**Comment by acsbendi** [comment]
@ryewilson Yes, I understand that. I would like to know the original justification for using `db.t2.small` rather than `db.t2.micro` too. We've been running Metaflow with a `db.t3.micro` for a couple of days and so far we haven't seen any issues.

**Review by oavdeev — APPROVED** [review]

**Comment by ryewilson** [comment]
@oavdeev Can you merge if it's good to go?

**Pull request merged**
